package com.xing.bluetoothweighapp.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xing.bluetoothweighapp.db.entity.WeightOrderBean;

import com.xing.bluetoothweighapp.dao.WeightOrderBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weightOrderBeanDaoConfig;

    private final WeightOrderBeanDao weightOrderBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weightOrderBeanDaoConfig = daoConfigMap.get(WeightOrderBeanDao.class).clone();
        weightOrderBeanDaoConfig.initIdentityScope(type);

        weightOrderBeanDao = new WeightOrderBeanDao(weightOrderBeanDaoConfig, this);

        registerDao(WeightOrderBean.class, weightOrderBeanDao);
    }
    
    public void clear() {
        weightOrderBeanDaoConfig.clearIdentityScope();
    }

    public WeightOrderBeanDao getWeightOrderBeanDao() {
        return weightOrderBeanDao;
    }

}
